version: "3.5"
services:
  beacon-chain:
    build:
      context: beacon-chain
      args:
        NETWORK: sepolia
        P2P_PORT: 9804
    ports:
      - "9804:9804"
      - "9804:9804/udp"
    environment:
      CORSDOMAIN: "http://lighthouse-sepolia.dappnode"
      CHECKPOINT_SYNC_URL: "https://checkpoint-sync-sepolia.dappnode.net"
  validator:
    build:
      args:
        NETWORK: sepolia
